const express = require('express');
const authController = require('../controllers/portal/auth/auth_controller');
const subscriptionController = require('../controllers/portal/content/SubscriptionController');
const streamController = require('../controllers/portal/content/StreamController');
const teachersController = require('../controllers/portal/content/TeachersController');
const learnersController = require('../controllers/portal/content/LearnerController');
const enrollmentController = require('../controllers/portal/content/EnrollmentController');
const parentsController = require('../controllers/portal/content/ParentController');
const PaymentsController = require('../controllers/payment/PaymentController');
const AssessmentController = require('../controllers/portal/content/AssessmentContoller');
const listLearningAreasController = require('../controllers/portal/content/learning_controller');
const schoolLearningAreaController = require('../controllers/portal/content/school_learning_area_controller');
const strandController = require('../controllers/portal/content/strand_controller');
const substrandController = require('../controllers/portal/content/substrand_controller');
const gradesController = require('../controllers/portal/content/grade_controller');
const roles_controller = require('../controllers/portal/auth/roles');
const usersController = require('../controllers/portal/auth/users_controller');
const schoolController = require('../controllers/portal/content/SchoolsController');
const teacherGradeAssignmet = require('../controllers/portal/content/TeacherGradeAssignment');
const testController = require('../controllers/portal/content/TestController');
const SummativeController = require('../controllers/portal/content/SummativeController');
const GradingController = require('../controllers/portal/content/GradingController');
const PackageController = require('../controllers/portal/content/PackageController');
//scheme
const SchemeController = require('../controllers/portal/content/SchemeController');
//lessonplancontroller
const LessonPlanController = require('../controllers/portal/content/LessonPlanController');
const DashboardController = require('../controllers/portal/content/DashboardController');
const transferRequestRoutes = require('../controllers/portal/content/TransferController');
const PlScaleController = require('../controllers/portal/content/PlScaleController');
const MetaDataController = require('../controllers/portal/auth/metadata_controller');
const BehaviourController = require('../controllers/portal/content/BehaviourController');
const CommentsController = require('../controllers/portal/content/CommentController');
const AttendanceController = require('../controllers/portal/content/AttendanceController');
const MessagesController = require('../controllers/portal/content/MessagesController');
const Notification = require('../controllers/portal/content/NotificationsCotroller');
const NoticeBoard = require('../controllers/portal/content/NoticeboardController');
const TimetableController = require('../controllers/portal/content/TimetableController');
const LevelController = require('../controllers/portal/content/level_controller');
const feeItemRoutes = require('./portal/content/feeItemRoutes');
const feeStructureRoutes = require('./portal/content/feeStructureRoutes');
const {auth} = require('../middleware/portal-auth');
const SubscriptionService = require('../services/portal/Subscription');
const {Attendance} = require('../services/portal/AttendanceService');
const router = express.Router();
router.use('/meta', MetaDataController);
router.use('/attendance', auth, AttendanceController);
//scheme
router.use('/scheme', auth, SchemeController);
router.use('/behaviour', auth, BehaviourController);
router.use('/grading-scale', auth, PlScaleController);
router.use('/auth', authController);
router.use('/subscription', auth, subscriptionController);
router.use('/teachers', auth, teachersController);
router.use('/learners', auth, learnersController);
router.use('/streams', auth, streamController);
router.use('/enrollment', auth, enrollmentController);
router.use('/parents', auth, parentsController);
router.use('/assessment', auth, AssessmentController);
router.use('/learning-areas', auth, listLearningAreasController);
router.use('/school-learning-areas', auth, schoolLearningAreaController);
router.use('/strand/', auth, strandController);
router.use('/substrand', auth, substrandController);
router.use('/users', auth, usersController);
router.use('/roles', auth, roles_controller);
router.use('/school', auth, schoolController);
router.use('/grade-teacher-assignment', auth, teacherGradeAssignmet);
router.use('/tests', auth, testController);
router.use('/grading-system', auth, PlScaleController);
router.use('/summative', auth, SummativeController);
router.use('/grades', auth, gradesController);
router.use('/dashboard', auth, DashboardController);
router.use('/transfer-requests', auth, transferRequestRoutes);
router.use('/payments', PaymentsController);
router.use('/package', PackageController);
router.use('/comment', auth, CommentsController);
router.use('/lesson-plan', auth, LessonPlanController);
// router.use('/comment', auth, CommentsController);
router.use('/noticeboard', auth, NoticeBoard);
router.use('/notifications', auth, Notification);
router.use('/messages', auth, MessagesController);
router.use('/timetable', auth, TimetableController);
router.use('/level', auth, LevelController);
router.use('/fee-items', auth, feeItemRoutes);
router.use('/fee-structures', auth, feeStructureRoutes);

router.use('/elimurise', express.static('/elimurise'));
router.get('/health', async (req, res) => {
  return res.status(200).json({status: 'up and running'});
});

module.exports = router;
